import { Setting } from "./types";

/**
 * Androidはメーカーごとに表示名が少し異なるため、Pixel系の標準Androidを基準にする。
 * Galaxyなどで項目名が異なる場合は、記事の分岐欄を追加してから公開する。
 */
export const androidSettings: Omit<Setting, "id" | "updated_at">[] = [
  {
    title: "Wi-Fiに接続する", slug: "connect-wifi-android", os: "android", version: "16",
    category: "network", aliases: ["WiFi接続", "ワイファイ", "無線LAN", "ネットにつなぐ"],
    path: ["設定", "ネットワークとインターネット", "インターネット"],
    steps: ["「設定」アプリを開く", "「ネットワークとインターネット」→「インターネット」をタップ", "Wi-Fiをオンにする", "接続したいネットワーク名をタップ", "パスワードを入力して「接続」をタップ"],
    related_slugs: ["connect-wifi-ios", "change-dns-android"], keywords: ["Wi-Fi", "WiFi", "接続", "ネットワーク", "パスワード"],
    description: "AndroidスマートフォンをWi-Fiに接続する方法です。Pixel系の標準Androidを基準にしています。",
    difficulty: "beginner", estimate_minutes: 2, device_scope: "Pixelなど標準Android（メーカーにより項目名が異なります）",
  },
  {
    title: "Bluetooth機器を接続する", slug: "connect-bluetooth-android", os: "android", version: "16",
    category: "bluetooth", aliases: ["Bluetooth接続", "ブルートゥース", "イヤホン接続", "ペアリング", "ワイヤレス接続"],
    path: ["設定", "接続済みのデバイス", "新しいデバイスとペア設定する"],
    steps: ["「設定」アプリを開く", "「接続済みのデバイス」をタップ", "「新しいデバイスとペア設定する」をタップ", "機器をペアリングモードにする", "表示された機器名をタップして接続"],
    related_slugs: ["connect-bluetooth", "connect-bluetooth-ios"], keywords: ["Bluetooth", "ブルートゥース", "ペアリング", "イヤホン", "接続"],
    description: "AndroidでイヤホンやスピーカーなどのBluetooth機器を接続する方法です。",
    difficulty: "beginner", estimate_minutes: 3,
  },
  {
    title: "画面の明るさを変更する", slug: "change-brightness-android", os: "android", version: "16",
    category: "display", aliases: ["明るさ", "輝度", "画面暗く", "まぶしい", "ブライトネス"],
    path: ["設定", "ディスプレイ", "明るさのレベル"],
    steps: ["「設定」アプリを開く", "「ディスプレイ」をタップ", "「明るさのレベル」をタップ", "スライダーを左右に動かして調整"],
    related_slugs: ["change-brightness", "change-brightness-ios", "night-light-android"], keywords: ["明るさ", "輝度", "暗い", "まぶしい", "ディスプレイ"],
    description: "Androidの画面の明るさを調整する方法です。クイック設定の明るさスライダーからも変更できます。",
    difficulty: "beginner", estimate_minutes: 1,
  },
  {
    title: "夜間モードを設定する", slug: "night-light-android", os: "android", version: "16",
    category: "display", aliases: ["ナイトライト", "ブルーライト", "夜間モード", "目に優しい", "暖色"],
    path: ["設定", "ディスプレイ", "夜間モード"],
    steps: ["「設定」アプリを開く", "「ディスプレイ」をタップ", "「夜間モード」をタップ", "今すぐオンにするか、スケジュールを設定する"],
    related_slugs: ["change-brightness-android"], keywords: ["ナイトライト", "ブルーライト", "夜間", "暖色", "ディスプレイ"],
    description: "Androidの画面を暖色にし、夜間に見やすくする方法です。",
    difficulty: "beginner", estimate_minutes: 2,
  },
  {
    title: "アプリの通知をオフにする", slug: "disable-notifications-android", os: "android", version: "16",
    category: "notification", aliases: ["通知オフ", "通知消したい", "通知うるさい", "アプリ通知", "通知を止める"],
    path: ["設定", "通知", "アプリの通知"],
    steps: ["「設定」アプリを開く", "「通知」をタップ", "「アプリの通知」をタップ", "通知を止めたいアプリを選ぶ", "「すべての通知」または個別の通知種類をオフにする"],
    related_slugs: ["disable-notifications", "disable-notifications-ios"], keywords: ["通知", "オフ", "消す", "アプリ", "サイレント"],
    description: "Androidでアプリごとの通知を止める方法です。通知の種類ごとに個別設定もできます。",
    difficulty: "beginner", estimate_minutes: 2,
  },
  {
    title: "アプリのマイク使用を許可する", slug: "allow-microphone-android", os: "android", version: "16",
    category: "privacy", aliases: ["マイク許可", "マイク使えない", "マイク設定", "音声入力", "アプリ権限"],
    path: ["設定", "セキュリティとプライバシー", "プライバシー", "権限マネージャー", "マイク"],
    steps: ["「設定」アプリを開く", "「セキュリティとプライバシー」→「プライバシー」をタップ", "「権限マネージャー」→「マイク」をタップ", "アプリを選び、「アプリの使用中のみ許可」などを選択"],
    related_slugs: ["allow-microphone", "allow-microphone-ios"], keywords: ["マイク", "許可", "権限", "プライバシー", "音声"],
    description: "Androidアプリがマイクを使えるように権限を変更する方法です。",
    difficulty: "beginner", estimate_minutes: 2,
  },
  {
    title: "アプリのカメラ使用を許可する", slug: "allow-camera-android", os: "android", version: "16",
    category: "privacy", aliases: ["カメラ許可", "カメラ使えない", "ビデオ通話", "カメラ権限", "撮影できない"],
    path: ["設定", "セキュリティとプライバシー", "プライバシー", "権限マネージャー", "カメラ"],
    steps: ["「設定」アプリを開く", "「セキュリティとプライバシー」→「プライバシー」をタップ", "「権限マネージャー」→「カメラ」をタップ", "アプリを選び、カメラの使用を許可する"],
    related_slugs: ["allow-camera", "allow-microphone-android"], keywords: ["カメラ", "許可", "権限", "プライバシー", "ビデオ"],
    description: "Androidアプリがカメラを使えるように権限を変更する方法です。",
    difficulty: "beginner", estimate_minutes: 2,
  },
  {
    title: "位置情報をオフにする", slug: "disable-location-android", os: "android", version: "16",
    category: "privacy", aliases: ["位置情報オフ", "GPS", "場所の許可", "位置情報設定", "現在地を止める"],
    path: ["設定", "位置情報"],
    steps: ["「設定」アプリを開く", "「位置情報」をタップ", "「位置情報を使用」をオフにする", "特定のアプリだけ変更する場合は「アプリへの位置情報の利用許可」から選ぶ"],
    related_slugs: ["allow-microphone-android", "disable-notifications-android"], keywords: ["位置情報", "GPS", "プライバシー", "現在地", "場所"],
    description: "Android全体、またはアプリごとの位置情報利用を変更する方法です。",
    difficulty: "beginner", estimate_minutes: 1,
  },
  {
    title: "バッテリーセーバーをオンにする", slug: "battery-saver-android", os: "android", version: "16",
    category: "system", aliases: ["バッテリー節約", "省電力", "節電", "電池長持ち", "充電が減る"],
    path: ["設定", "バッテリー", "バッテリー セーバー"],
    steps: ["「設定」アプリを開く", "「バッテリー」をタップ", "「バッテリー セーバー」をタップ", "「今すぐ使用」をオンにする"],
    related_slugs: ["battery-save-ios", "change-brightness-android"], keywords: ["バッテリー", "節約", "省電力", "電池", "セーバー"],
    description: "Androidのバッテリーセーバーをオンにして電池を長持ちさせる方法です。",
    difficulty: "beginner", estimate_minutes: 1,
  },
  {
    title: "ストレージの空き容量を確認する", slug: "check-storage-android", os: "android", version: "16",
    category: "storage", aliases: ["容量確認", "ストレージ不足", "空き容量", "内部ストレージ", "GB確認"],
    path: ["設定", "ストレージ"],
    steps: ["「設定」アプリを開く", "「ストレージ」をタップ", "使用中の容量と空き容量を確認する", "必要ならカテゴリをタップして不要なデータを整理する"],
    related_slugs: ["check-storage-ios", "battery-saver-android"], keywords: ["ストレージ", "容量", "空き", "GB", "内部"],
    description: "Androidのストレージ使用量と空き容量を確認する方法です。",
    difficulty: "beginner", estimate_minutes: 1,
  },
  {
    title: "画面ロックを設定する", slug: "setup-screen-lock-android", os: "android", version: "16",
    category: "security", aliases: ["画面ロック", "PIN設定", "パスワード設定", "パターンロック", "スマホにロック"],
    path: ["設定", "セキュリティとプライバシー", "デバイスのロック解除", "画面ロック"],
    steps: ["「設定」アプリを開く", "「セキュリティとプライバシー」をタップ", "「デバイスのロック解除」→「画面ロック」をタップ", "PIN、パターン、パスワードなどを選び、画面の指示に従う"],
    related_slugs: ["setup-lock-screen", "setup-fingerprint-android"], keywords: ["ロック", "PIN", "パスワード", "パターン", "セキュリティ"],
    description: "AndroidスマートフォンにPIN・パターン・パスワードなどの画面ロックを設定する方法です。",
    difficulty: "beginner", estimate_minutes: 3,
  },
  {
    title: "指紋認証を設定する", slug: "setup-fingerprint-android", os: "android", version: "16",
    category: "security", aliases: ["指紋認証", "生体認証", "指紋設定", "指でロック解除", "Fingerprint"],
    path: ["設定", "セキュリティとプライバシー", "デバイスのロック解除", "指紋認証"],
    steps: ["画面ロック用のPINなどを設定する", "「設定」→「セキュリティとプライバシー」を開く", "「デバイスのロック解除」→「指紋認証」をタップ", "画面の指示に従い、指紋を登録する"],
    related_slugs: ["setup-screen-lock-android"], keywords: ["指紋", "認証", "生体認証", "ロック解除", "セキュリティ"],
    description: "Androidで指紋認証を登録し、ロック解除に使う方法です。",
    difficulty: "beginner", estimate_minutes: 3,
  },
  {
    title: "文字サイズを変更する", slug: "change-font-size-android", os: "android", version: "16",
    category: "accessibility", aliases: ["文字サイズ", "フォントサイズ", "文字大きく", "テキストサイズ", "見やすく"],
    path: ["設定", "ディスプレイとタップ", "表示サイズとテキスト"],
    steps: ["「設定」アプリを開く", "「ディスプレイとタップ」をタップ", "「表示サイズとテキスト」をタップ", "「フォントサイズ」のスライダーを動かして調整する"],
    related_slugs: ["change-text-size-ios"], keywords: ["フォント", "文字", "サイズ", "大きく", "見やすい"],
    description: "Androidの文字サイズを大きくしたり小さくしたりする方法です。",
    difficulty: "beginner", estimate_minutes: 1,
  },
  {
    title: "着信音を変更する", slug: "change-ringtone-android", os: "android", version: "16",
    category: "sound", aliases: ["着信音", "着信音変更", "サウンド", "通知音", "リングトーン"],
    path: ["設定", "音とバイブレーション", "着信音"],
    steps: ["「設定」アプリを開く", "「音とバイブレーション」をタップ", "「着信音」をタップ", "着信音を選び、「保存」または戻る操作で確定する"],
    related_slugs: ["change-ringtone-ios", "disable-notifications-android"], keywords: ["着信音", "サウンド", "通知音", "リングトーン", "音"],
    description: "Androidの電話着信音を変更する方法です。",
    difficulty: "beginner", estimate_minutes: 2,
  },
  {
    title: "開発者向けオプションを有効にする", slug: "developer-options-android", os: "android", version: "16",
    category: "system", aliases: ["開発者オプション", "デベロッパーモード", "USBデバッグ", "開発者設定", "デバッグ"],
    path: ["設定", "デバイス情報", "ビルド番号"],
    steps: ["「設定」アプリを開く", "「デバイス情報」をタップ", "「ビルド番号」を7回連続でタップする", "確認を求められたら画面ロックのPINなどを入力する", "設定に戻ると「開発者向けオプション」が表示される"],
    related_slugs: [], keywords: ["開発者", "デベロッパー", "USB", "デバッグ", "ビルド番号"],
    description: "Androidの開発者向けオプションを有効にする方法です。不要な項目は変更しないでください。",
    difficulty: "advanced", estimate_minutes: 2, caution: "意味が分からない項目を変更すると、動作やセキュリティに影響する場合があります。",
  },
  {
    title: "スクリーンショットを撮る", slug: "take-screenshot-android", os: "android", version: "16",
    category: "system", aliases: ["スクショ", "画面キャプチャ", "画面保存", "スクリーンキャプチャ", "スクリーンショット"],
    path: ["電源ボタン", "音量を下げるボタン"],
    steps: ["撮影したい画面を表示する", "電源ボタンと音量を下げるボタンを同時に押す", "画面のプレビューまたは通知から撮影結果を確認する"],
    related_slugs: ["take-screenshot", "screenshot-macos"], keywords: ["スクリーンショット", "スクショ", "キャプチャ", "画面", "保存"],
    description: "Androidスマートフォンで画面のスクリーンショットを撮る方法です。",
    difficulty: "beginner", estimate_minutes: 1,
  },
];
