import { Setting } from "./types";

/**
 * 主対象（Windows 11 / iPhone / Android）の「困っている」検索を受け止める記事。
 * メーカーや通信会社による差が大きい領域なので、共通手順と公式ヘルプへの導線を分けて管理する。
 */
export const primarySettings: Omit<Setting, "id" | "updated_at">[] = [
  {
    title: "Wi-Fiが切れる・つながらないときの対処",
    slug: "wifi-troubleshoot-windows11",
    os: "windows11",
    version: "25H2",
    category: "network",
    aliases: ["Wi-Fi切れる", "WiFi切れる", "Wi-Fiつながらない", "WiFi繋がらない", "ネット切れる", "Wi-Fi不安定"],
    path: ["設定", "ネットワークとインターネット", "Wi-Fi"],
    steps: [
      "タスクバーのネットワークアイコンをクリックし、Wi-Fiをいったんオフ→オンにする",
      "設定（Win + I）→「ネットワークとインターネット」→「Wi-Fi」で接続先を確認する",
      "接続先を選び、「切断」してから再接続する",
      "改善しない場合は「既知のネットワークの管理」から対象Wi-Fiを選び、「削除」してパスワードを入力し直す",
      "複数の端末で切れる場合は、ルーターを再起動してから再確認する",
    ],
    related_slugs: ["change-dns"],
    keywords: ["Wi-Fi", "WiFi", "無線LAN", "接続", "切断", "インターネット", "ネットワーク", "トラブル"],
    description: "Windows 11でWi-Fiが切れる、つながらない、接続が不安定なときに確認する順番です。",
    difficulty: "beginner",
    estimate_minutes: 5,
    source_url: "https://support.microsoft.com/en-us/windows/experience/connectivity-networking/connect-to-a-wi-fi-network-in-windows",
    verified_at: "2026-08-13T00:00:00.000Z",
    device_scope: "Windows 11 25H2。PCメーカーの無線ドライバーやルーターによって表示が異なる場合があります。",
    impact: "Wi-Fiの登録を削除すると、再接続時にパスワードの入力が必要です。",
    rollback: "削除したWi-Fiを一覧から選び、パスワードを入力して再登録します。",
  },
  {
    title: "Wi-Fiが切れる・つながらないときの対処",
    slug: "wifi-troubleshoot-ios",
    os: "ios",
    version: "26",
    category: "network",
    aliases: ["Wi-Fi切れる", "WiFi切れる", "Wi-Fiつながらない", "WiFi繋がらない", "ネット切れる", "Wi-Fi不安定"],
    path: ["設定", "Wi-Fi"],
    steps: [
      "「設定」→「Wi-Fi」を開き、Wi-Fiをいったんオフ→オンにする",
      "接続先のネットワーク名をタップし、「このネットワーク設定を削除」を選ぶ",
      "確認画面で削除したあと、同じネットワークを選び、パスワードを入力して再接続する",
      "改善しない場合はiPhoneを再起動し、ルーターに近い場所で再確認する",
      "どのWi-Fiにもつながらない場合は、Appleの公式サポート手順を確認する",
    ],
    related_slugs: ["connect-wifi-ios"],
    keywords: ["Wi-Fi", "WiFi", "無線LAN", "接続", "切断", "インターネット", "ネットワーク", "トラブル"],
    description: "iPhoneでWi-Fiが切れる、つながらない、接続が不安定なときの確認手順です。",
    difficulty: "beginner",
    estimate_minutes: 5,
    source_url: "https://support.apple.com/en-us/111786",
    verified_at: "2026-08-13T00:00:00.000Z",
    device_scope: "iOS 26。iOSのバージョンやネットワーク構成により項目名が異なる場合があります。",
    impact: "ネットワーク設定を削除すると、保存済みパスワードが消える場合があります。",
    rollback: "同じネットワークを選び、Wi-Fiパスワードを入力して再接続します。",
  },
  {
    title: "Wi-Fiが切れる・つながらないときの対処",
    slug: "wifi-troubleshoot-android",
    os: "android",
    version: "16",
    category: "network",
    aliases: ["Wi-Fi切れる", "WiFi切れる", "Wi-Fiつながらない", "WiFi繋がらない", "ネット切れる", "Wi-Fi不安定"],
    path: ["設定", "ネットワークとインターネット", "インターネット"],
    steps: [
      "「設定」→「ネットワークとインターネット」→「インターネット」を開く",
      "Wi-Fiをいったんオフ→オンにし、接続先を選び直す",
      "接続先を長押しして保存済みネットワークから削除し、パスワードを入力して再接続する",
      "クイック設定の「インターネット」から「リセット」が表示される場合は、接続をリセットする",
      "複数の端末で切れる場合は、ルーターを再起動してから再確認する",
    ],
    related_slugs: ["connect-wifi-android"],
    keywords: ["Wi-Fi", "WiFi", "無線LAN", "接続", "切断", "インターネット", "ネットワーク", "トラブル"],
    description: "AndroidスマートフォンでWi-Fiが切れる、つながらない、接続が不安定なときの確認手順です。",
    difficulty: "beginner",
    estimate_minutes: 5,
    source_url: "https://support.google.com/android/answer/2651367?hl=ja",
    verified_at: "2026-08-13T00:00:00.000Z",
    device_scope: "Android 16の標準的な設定画面（Pixel系）を基準にしています。Galaxyなどでは項目名が異なります。",
    impact: "保存済みネットワークを削除すると、再接続時にパスワードの入力が必要です。",
    rollback: "削除したWi-Fiを一覧から選び、パスワードを入力して再登録します。",
  },
];
