import { Setting } from "./types";

/**
 * 主対象（Windows 11 / iPhone / Android）の「困っている」検索を受け止める記事。
 * メーカーや通信会社による差が大きい領域なので、共通手順と公式ヘルプへの導線を分けて管理する。
 */
export const primarySettings: Omit<Setting, "id" | "updated_at">[] = [
  {
    title: "Wi-Fiが切れる・つながらないときの対処",
    slug: "wifi-troubleshoot-windows11",
    os: "windows11",
    version: "25H2",
    category: "network",
    aliases: ["Wi-Fi切れる", "WiFi切れる", "Wi-Fiつながらない", "WiFi繋がらない", "ネット切れる", "Wi-Fi不安定"],
    path: ["設定", "ネットワークとインターネット", "Wi-Fi"],
    steps: [
      "タスクバーのネットワークアイコンをクリックし、Wi-Fiをいったんオフ→オンにする",
      "設定（Win + I）→「ネットワークとインターネット」→「Wi-Fi」で接続先を確認する",
      "接続先を選び、「切断」してから再接続する",
      "改善しない場合は「既知のネットワークの管理」から対象Wi-Fiを選び、「削除」してパスワードを入力し直す",
      "複数の端末で切れる場合は、ルーターを再起動してから再確認する",
    ],
    related_slugs: ["change-dns"],
    keywords: ["Wi-Fi", "WiFi", "無線LAN", "接続", "切断", "インターネット", "ネットワーク", "トラブル"],
    description: "Windows 11でWi-Fiが切れる、つながらない、接続が不安定なときに確認する順番です。",
    difficulty: "beginner",
    estimate_minutes: 5,
    source_url: "https://support.microsoft.com/en-us/windows/experience/connectivity-networking/connect-to-a-wi-fi-network-in-windows",
    verified_at: "2026-08-13T00:00:00.000Z",
    device_scope: "Windows 11 25H2。PCメーカーの無線ドライバーやルーターによって表示が異なる場合があります。",
    impact: "Wi-Fiの登録を削除すると、再接続時にパスワードの入力が必要です。",
    rollback: "削除したWi-Fiを一覧から選び、パスワードを入力して再登録します。",
  },
  {
    title: "Windows 11で集中モードが通知を隠しているときの対処",
    slug: "trouble13-unique-win-focus-assist-hidden",
    os: "windows11",
    version: "25H2",
    category: "notification",
    aliases: ["Windows通知が表示されない", "集中モードで通知が来ない", "応答不可で通知が隠れる", "フォーカスアシスト通知"],
    path: ["設定", "システム", "通知", "応答不可"],
    steps: [
      "「設定」→「システム」→「通知」を開く",
      "「応答不可」がオンになっていないか確認し、必要なければオフにする",
      "自動的にオンになるスケジュールや条件があれば確認する",
      "通知を許可するアプリや優先通知の設定を確認する",
      "設定後、対象アプリからテスト通知を送って表示を確認する",
    ],
    related_slugs: ["disable-notifications", "teams-notification-sounds"],
    keywords: ["Windows 11", "通知", "表示されない", "集中モード", "応答不可", "フォーカスアシスト"],
    description: "Windows 11で集中モードや応答不可が通知を隠していないか確認する方法です。",
    source_url: "https://support.microsoft.com/ja-jp/windows/experience/notifications-and-do-not-disturb-in-windows",
    source_type: "OFFICIAL_SUPPORT",
    device_scope: "Windows 11 25H2。更新状況やPCメーカー、組織のポリシーによって項目名が異なる場合があります。",
    impact: "応答不可をオフにすると、通知バナーや通知音が表示されるようになります。作業中の通知も増える可能性があります。",
    rollback: "同じ通知設定を開き、応答不可や自動スケジュールを元の設定に戻します。",
    caution: "通知を許可すると、会議中やロック画面に内容が表示される場合があります。",
    if_missing: "設定アプリ内で「通知」「応答不可」「集中」を検索してください。組織PCでは管理者設定も確認します。",
  },
  {
    title: "Wi-Fiが切れる・つながらないときの対処",
    slug: "wifi-troubleshoot-ios",
    os: "ios",
    version: "26",
    category: "network",
    aliases: ["Wi-Fi切れる", "WiFi切れる", "Wi-Fiつながらない", "WiFi繋がらない", "ネット切れる", "Wi-Fi不安定"],
    path: ["設定", "Wi-Fi"],
    steps: [
      "「設定」→「Wi-Fi」を開き、Wi-Fiをいったんオフ→オンにする",
      "接続先のネットワーク名をタップし、「このネットワーク設定を削除」を選ぶ",
      "確認画面で削除したあと、同じネットワークを選び、パスワードを入力して再接続する",
      "改善しない場合はiPhoneを再起動し、ルーターに近い場所で再確認する",
      "どのWi-Fiにもつながらない場合は、Appleの公式サポート手順を確認する",
    ],
    related_slugs: ["connect-wifi-ios"],
    keywords: ["Wi-Fi", "WiFi", "無線LAN", "接続", "切断", "インターネット", "ネットワーク", "トラブル"],
    description: "iPhoneでWi-Fiが切れる、つながらない、接続が不安定なときの確認手順です。",
    difficulty: "beginner",
    estimate_minutes: 5,
    source_url: "https://support.apple.com/en-us/111786",
    verified_at: "2026-08-13T00:00:00.000Z",
    device_scope: "iOS 26。iOSのバージョンやネットワーク構成により項目名が異なる場合があります。",
    impact: "ネットワーク設定を削除すると、保存済みパスワードが消える場合があります。",
    rollback: "同じネットワークを選び、Wi-Fiパスワードを入力して再接続します。",
  },
  {
    title: "Wi-Fiが切れる・つながらないときの対処",
    slug: "wifi-troubleshoot-android",
    os: "android",
    version: "16",
    category: "network",
    aliases: ["Wi-Fi切れる", "WiFi切れる", "Wi-Fiつながらない", "WiFi繋がらない", "ネット切れる", "Wi-Fi不安定"],
    path: ["設定", "ネットワークとインターネット", "インターネット"],
    steps: [
      "「設定」→「ネットワークとインターネット」→「インターネット」を開く",
      "Wi-Fiをいったんオフ→オンにし、接続先を選び直す",
      "接続先を長押しして保存済みネットワークから削除し、パスワードを入力して再接続する",
      "クイック設定の「インターネット」から「リセット」が表示される場合は、接続をリセットする",
      "複数の端末で切れる場合は、ルーターを再起動してから再確認する",
    ],
    related_slugs: ["connect-wifi-android"],
    keywords: ["Wi-Fi", "WiFi", "無線LAN", "接続", "切断", "インターネット", "ネットワーク", "トラブル"],
    description: "AndroidスマートフォンでWi-Fiが切れる、つながらない、接続が不安定なときの確認手順です。",
    difficulty: "beginner",
    estimate_minutes: 5,
    source_url: "https://support.google.com/android/answer/2651367?hl=ja",
    verified_at: "2026-08-13T00:00:00.000Z",
    device_scope: "Android 16の標準的な設定画面（Pixel系）を基準にしています。Galaxyなどでは項目名が異なります。",
    impact: "保存済みネットワークを削除すると、再接続時にパスワードの入力が必要です。",
    rollback: "削除したWi-Fiを一覧から選び、パスワードを入力して再登録します。",
  },
  {
    title: "iPhoneの通知が来ない・表示されないときの対処",
    slug: "trouble-iphone-notifications",
    os: "ios",
    version: "26",
    category: "notification",
    aliases: ["iPhoneの通知が届かない", "iPhone通知が来ない", "通知表示されない", "LINE通知が来ない"],
    path: ["設定", "通知", "対象アプリの通知"],
    steps: [
      "「設定」→「通知」を開き、対象アプリを選ぶ",
      "「通知を許可」がオンで、ロック画面・通知センター・バナーの表示が必要な範囲でオンか確認する",
      "集中モードや通知の要約で、通知が遅れたり隠れたりしていないか確認する",
      "通知は表示されるが音だけ鳴らない場合は、消音モードと「サウンドと触覚」を確認する",
      "アプリとiOSを更新し、iPhoneを再起動してもう一度通知を確認する",
    ],
    related_slugs: ["disable-notifications-ios", "iphone-notification-sounds", "iphone-text-size"],
    keywords: ["iPhone", "通知", "通知来ない", "届かない", "表示されない", "集中モード", "通知の要約"],
    description: "iPhoneで通知が届かない、または表示されないときに、アプリごとの許可から確認する順番です。",
    source_url: "https://support.apple.com/ja-jp/guide/iphone/-iph7c3d96bab/ios",
    source_type: "OFFICIAL_DOCUMENTATION",
    device_scope: "iPhone（iOS 26を基準。アプリやiOSの版によって項目名・表示が異なる場合があります）",
    impact: "通知の許可や表示範囲を変えると、対象アプリのロック画面・通知センター・バナーへの表示が変わります。",
    rollback: "同じ対象アプリの通知設定を開き、変更した許可や表示方法を元に戻します。",
    caution: "通知を許可すると、ロック画面に内容が表示される場合があります。共有端末ではプレビュー設定も確認してください。",
    if_missing: "設定アプリ内で「通知」または対象アプリ名を検索してください。アプリ内の通知設定も確認します。",
  },
  {
    title: "iPhoneの通知音だけを消す",
    slug: "iphone-notification-sounds",
    os: "ios",
    version: "26",
    category: "sound",
    aliases: ["通知音を消したい", "iPhone通知音オフ", "アプリごとに通知音", "通知音だけ止めたい"],
    path: ["設定", "通知", "対象アプリ", "サウンド"],
    steps: [
      "「設定」→「通知」を開く",
      "通知音を消したいアプリを選ぶ",
      "「通知を許可」は必要に応じて残し、「サウンド」をオフにする",
      "通知音全体を調整する場合は「設定」→「サウンドと触覚」も確認する",
      "バナーやバッジは残したまま、音だけ変わったか通知を受けて確認する",
    ],
    related_slugs: ["disable-notifications-ios", "trouble-iphone-notifications"],
    keywords: ["iPhone", "通知音", "サウンド", "音だけ消す", "バイブレーション", "アプリ通知"],
    description: "iPhoneで通知の表示は残し、特定アプリの通知音だけを消す方法です。",
    source_url: "https://support.apple.com/ja-jp/guide/iphone/-iph7c3d96bab/ios",
    source_type: "OFFICIAL_DOCUMENTATION",
    device_scope: "iPhone（iOS 26を基準。アプリやiOSの版によって項目名・表示が異なる場合があります）",
    impact: "対象アプリの通知音が鳴らなくなります。バナーやバッジの表示は別に残せる場合があります。",
    rollback: "対象アプリの通知設定を開き、「サウンド」をオンに戻します。",
    if_missing: "設定アプリ内で「通知」または対象アプリ名を検索してください。アプリ側に通知音設定がある場合はそちらも確認します。",
  },
  {
    title: "Androidで通知が表示されないときの対処",
    slug: "trouble-android-notifications",
    os: "android",
    version: "16",
    category: "notification",
    aliases: ["Androidの通知が来ない", "Android通知表示されない", "LINE通知が来ない", "通知を表示したい"],
    path: ["設定", "通知", "アプリの通知"],
    steps: [
      "「設定」→「通知」→「アプリの通知」を開き、対象アプリを選ぶ",
      "アプリの通知と、通知カテゴリごとの許可状態を確認する",
      "おやすみ時間・サイレントモード・省電力設定で通知が抑えられていないか確認する",
      "通知が1件でも表示される場合は、その通知を長押しして重要度や表示方法を確認する。一切表示されない場合はこの手順を飛ばす",
      "アプリとAndroidを更新してから再起動し、通知をもう一度確認する",
    ],
    related_slugs: ["disable-notifications-android", "android-notification-history"],
    keywords: ["Android", "通知", "通知来ない", "届かない", "表示されない", "サイレント", "省電力"],
    description: "Androidで通知が届かない、または表示されないときに、アプリの通知から確認する順番です。",
    source_url: "https://support.google.com/android/answer/9079661?hl=ja",
    source_type: "OFFICIAL_SUPPORT",
    device_scope: "Android 16の標準的な設定画面を基準にしています。メーカー・機種・Androidの版によって項目名が異なります。",
    impact: "通知の許可や省電力の設定を変えると、対象アプリの通知表示・動作時間・電池消費に影響します。",
    rollback: "同じ通知・アプリ・バッテリー設定を開き、変更した許可や最適化を元に戻します。",
    caution: "省電力の制限を緩めると電池の減りが早くなる場合があります。必要なアプリだけ変更してください。",
    if_missing: "設定アプリ内で「通知」または対象アプリ名を検索してください。メーカー独自の通知管理も確認します。",
  },
  {
    title: "Androidアプリの通知音だけを消す",
    slug: "android-guide-notification-channels",
    os: "android",
    version: "16",
    category: "notification",
    aliases: ["Android通知音を消したい", "通知音だけオフ", "アプリ通知音だけ止める", "通知カテゴリの音を消す"],
    path: ["設定", "通知", "アプリの通知", "通知カテゴリ"],
    steps: [
      "「設定」→「通知」→「アプリの通知」を開く",
      "通知音を消したいアプリを選ぶ",
      "通知カテゴリまたは通知の種類を開く",
      "必要なカテゴリだけ、音とバイブレーションをオフにする。表示は残せる場合があります",
      "通知が表示されるが音だけ消えたことを確認する",
    ],
    related_slugs: ["disable-notifications-android", "android-notification-history"],
    keywords: ["Android", "通知音", "サウンド", "通知カテゴリ", "音だけ消す", "バイブレーション"],
    description: "Androidで通知を画面には表示しつつ、アプリの通知カテゴリごとに音だけを止める方法です。",
    source_url: "https://support.google.com/android/answer/9079661?hl=ja",
    source_type: "OFFICIAL_SUPPORT",
    device_scope: "Android 16の標準的な設定画面を基準にしています。メーカー・機種・アプリによって通知カテゴリの名称や設定範囲が異なります。",
    impact: "選んだ通知カテゴリの音やバイブレーションが止まります。重要な通知まで無音にしないようカテゴリを確認してください。",
    rollback: "同じ通知カテゴリを開き、音とバイブレーションをオンに戻します。",
    caution: "通知音を止めると、緊急性のある通知に気付きにくくなる場合があります。",
    if_missing: "アプリの通知設定に「通知カテゴリ」や種類の一覧がない場合は、アプリ内の通知設定を確認してください。",
  },
  {
    title: "Teamsの通知音だけを消す",
    slug: "teams-notification-sounds",
    os: "windows11",
    version: "25H2",
    category: "sound",
    aliases: ["Teams通知音", "Teams音うるさい", "Teamsサウンドオフ"],
    path: ["Teams", "設定", "通知とアクティビティ", "サウンド"],
    steps: [
      "Teamsを開き、プロフィール画像の横にある「…」をクリックする",
      "「設定」→「通知とアクティビティ」を開く",
      "「サウンド」を選ぶ",
      "不要な通知のサウンドをオフにする",
      "必要ならテスト通知で、バナーを残して音だけ止まったことを確認する",
    ],
    related_slugs: ["disable-notifications"],
    keywords: ["Teams", "通知音", "サウンド", "音だけ消す", "Microsoft Teams"],
    description: "Windows 11のTeamsで、バナー通知は残したまま通知音だけを止める方法です。",
    source_url: "https://support.microsoft.com/en-us/teams/notifications-settings/manage-notifications-in-microsoft-teams",
    source_type: "OFFICIAL_SUPPORT",
    device_scope: "Windows 11上のTeamsデスクトップアプリを基準にしています。新しいTeams・Web版・組織ポリシーで表示が異なる場合があります。",
    impact: "Teamsの対象通知の音が鳴らなくなります。バナーやアクティビティへの表示は別に残せる場合があります。",
    rollback: "同じ「通知とアクティビティ」→「サウンド」を開き、必要な通知音をオンに戻します。",
    if_missing: "Teamsの設定内で「通知」または「サウンド」を検索してください。Web版とデスクトップ版を取り違えていないか確認します。",
  },
  {
    title: "Windows 11でBluetooth機器と接続できないときの対処",
    slug: "trouble-win11-bluetooth-pairing",
    os: "windows11",
    version: "25H2",
    category: "bluetooth",
    aliases: ["Bluetoothがつながらない", "イヤホンを認識しない", "マウスを接続できない"],
    path: ["設定", "Bluetoothとデバイス", "デバイス", "Bluetoothトラブルシューティング"],
    steps: [
      "Bluetoothがオンで、接続機器がペアリングモードになっているか確認する",
      "機器の電池・距離・周囲の電波干渉を確認する",
      "「設定」→「Bluetoothとデバイス」→「デバイス」で古い登録を削除する",
      "機器を再起動し、「デバイスの追加」から再登録する",
      "改善しない場合はWindowsのBluetoothトラブルシューティングを実行する",
    ],
    related_slugs: ["bluetooth-troubleshoot", "connect-bluetooth"],
    keywords: ["Windows 11", "Bluetooth", "ペアリングできない", "接続できない", "イヤホン"],
    description: "Windows 11でBluetooth機器が見つからない、または接続できないときの確認順です。",
    source_url: "https://support.microsoft.com/en-us/windows/hardware/bluetooth/fix-bluetooth-problems-in-windows",
    source_type: "OFFICIAL_SUPPORT",
    device_scope: "Windows 11 25H2。PCメーカーのドライバーや接続機器によって表示が異なる場合があります。",
    impact: "登録済み機器を削除すると、再接続時にペアリング操作が必要です。",
    rollback: "削除した機器を「デバイスの追加」から再登録します。",
    caution: "会社・学校の管理PCでは、ドライバー変更やトラブルシューティング前に管理者へ確認してください。",
    if_missing: "設定アプリ内で「Bluetooth」または「デバイスの追加」を検索してください。",
  },
  {
    title: "iPhoneでBluetooth機器がつながらないときの対処",
    slug: "trouble-iphone-bluetooth",
    os: "ios",
    version: "26",
    category: "bluetooth",
    aliases: ["iPhoneのBluetoothがつながらない", "イヤホンを認識しない", "車とiPhoneを接続"],
    path: ["設定", "Bluetooth", "このデバイスの登録を解除"],
    steps: [
      "機器をiPhoneの近くに置き、電源と充電状態を確認する",
      "機器を検出モードまたはペアリングモードにする",
      "「設定」→「Bluetooth」でBluetoothをオンにする",
      "登録済み機器の情報ボタンから「このデバイスの登録を解除」を選ぶ",
      "機器を再起動し、もう一度ペアリングする",
    ],
    related_slugs: ["connect-bluetooth-ios"],
    keywords: ["iPhone", "Bluetooth", "接続できない", "ペアリング", "イヤホン"],
    description: "iPhoneでBluetooth機器が見つからない、または接続できないときの確認順です。",
    source_url: "https://support.apple.com/en-us/111804",
    source_type: "OFFICIAL_SUPPORT",
    device_scope: "iPhone（iOS 26を基準。機器の種類やiOSの版によって表示が異なる場合があります）",
    impact: "登録を解除すると、機器の接続情報がiPhoneから削除されます。",
    rollback: "機器をペアリングモードにして、設定のBluetooth一覧から再登録します。",
    caution: "車載機器や医療機器などは、登録解除前に再接続方法を確認してください。",
    if_missing: "設定アプリ内で「Bluetooth」を検索してください。機器側の説明書でペアリングモードも確認します。",
  },
  {
    title: "AndroidでBluetooth機器がつながらないときの対処",
    slug: "trouble-android-bluetooth",
    os: "android",
    version: "16",
    category: "bluetooth",
    aliases: ["AndroidのBluetoothがつながらない", "車とスマホを接続できない", "Bluetoothイヤホン認識しない"],
    path: ["設定", "接続済みのデバイス", "Bluetooth", "保存済みのデバイス"],
    steps: [
      "Bluetoothをオフにしてからオンにする",
      "スマートフォンと接続機器を再起動する",
      "機器が検出モードで近くにあるか確認する",
      "「設定」→「接続済みのデバイス」で古い登録を削除する",
      "ペア設定を解除した機器を、もう一度ペアリングする",
    ],
    related_slugs: ["connect-bluetooth-android"],
    keywords: ["Android", "Bluetooth", "ペアリングできない", "イヤホン", "車"],
    description: "AndroidでBluetooth機器が見つからない、または接続できないときの確認順です。",
    source_url: "https://support.google.com/android/answer/9769184?hl=ja",
    source_type: "OFFICIAL_SUPPORT",
    device_scope: "Android 16の標準的な設定画面を基準にしています。メーカー・機種により項目名が異なります。",
    impact: "登録を削除すると、機器の接続情報が端末から削除されます。",
    rollback: "機器をペアリングモードにして、保存済みデバイスへ再登録します。",
    caution: "車や仕事用機器など、登録解除後の再接続にPINが必要な機器は情報を確認してから操作してください。",
    if_missing: "設定アプリ内で「Bluetooth」または「接続済みのデバイス」を検索してください。",
  },
  {
    title: "MacのBluetoothイヤホンの音が途切れるときの対処",
    slug: "trouble-mac-bluetooth-audio",
    os: "macos",
    version: "Tahoe 26",
    category: "bluetooth",
    aliases: ["MacのBluetooth音が途切れる", "AirPodsの音が切れる", "ワイヤレス音声が不安定"],
    path: ["システム設定", "Bluetooth", "サウンド", "登録解除と再接続"],
    steps: [
      "Macとイヤホンを近づけ、イヤホンの充電状態を確認する",
      "保存済みの音声ファイルを再生し、特定アプリだけの症状か切り分ける",
      "Wi-Fi機器や電子レンジなど、電波干渉源から離れて試す",
      "Bluetooth機器の登録を解除して、もう一度接続する",
      "改善しない場合はイヤホン側とmacOSを更新する",
    ],
    related_slugs: ["connect-bluetooth-macos"],
    keywords: ["Mac", "Bluetooth", "イヤホン", "音が途切れる", "音が飛ぶ"],
    description: "MacでBluetoothイヤホンの音が途切れるときに、距離・干渉・登録情報を確認する順番です。",
    source_url: "https://support.apple.com/en-us/102530",
    source_type: "OFFICIAL_SUPPORT",
    device_scope: "Mac（macOS Tahoe 26を基準。Macの機種や接続機器によって表示が異なる場合があります）",
    impact: "機器の登録を解除すると、再接続時にペアリング操作が必要です。",
    rollback: "Bluetooth一覧から機器を再度選び、接続またはペアリングします。",
    caution: "会社の会議機器などは登録解除前に再接続に必要な情報を確認してください。",
    if_missing: "システム設定内で「Bluetooth」または「サウンド」を検索してください。",
  },
  {
    title: "MacがWi-Fiにつながらないときの対処",
    slug: "trouble-mac-wifi",
    os: "macos",
    version: "Tahoe 26",
    category: "network",
    aliases: ["MacのWiFiが切れる", "Macネットにつながらない", "Mac無線LANトラブル"],
    path: ["システム設定", "Wi-Fi", "Wi-Fiの状態", "ワイヤレス診断"],
    steps: [
      "メニューバーまたはコントロールセンターでWi-Fiがオンか確認する",
      "Macをルーターの近くへ移動し、Wi-Fiを一度オフにしてからオンにする",
      "別のネットワークでも接続できるか確認する",
      "ルーターを再起動し、他の端末でも同じ症状か切り分ける",
      "改善しない場合はOptionキーを押しながらWi-Fiメニューを開き、ワイヤレス診断を確認する",
    ],
    related_slugs: [],
    keywords: ["Mac", "macOS", "Wi-Fiつながらない", "ネット接続", "ワイヤレス診断"],
    description: "MacでWi-Fiが切れる、つながらないときに、Mac側・ルーター側を切り分ける順番です。",
    source_url: "https://support.apple.com/guide/mac-help/if-you-cant-connect-to-a-wi-fi-network-on-mac-mchlp1185/mac",
    source_type: "OFFICIAL_DOCUMENTATION",
    device_scope: "Mac（macOS Tahoe 26を基準。macOSの版やネットワーク構成により表示が異なる場合があります）",
    impact: "ネットワーク設定を削除する操作は含めていません。接続先を変えると通信経路が変わります。",
    rollback: "元のWi-Fiネットワークを一覧から選び、パスワードを入力して再接続します。",
    caution: "会社・学校のネットワークでは、設定変更や診断前に管理者へ確認してください。",
    if_missing: "システム設定内で「Wi-Fi」または「ワイヤレス診断」を検索してください。",
  },
];
