import { Setting } from "./types";

export const sampleSettings: Omit<Setting, "id" | "updated_at">[] = [
  // === Windows 11 ===
  {
    title: "ファイル拡張子を表示する",
    slug: "show-file-extensions",
    os: "windows11",
    version: "23H2",
    category: "file",
    aliases: ["拡張子表示", "拡張子を見たい", "ファイルの種類", ".txtが見えない", "拡張子が消えた"],
    path: ["エクスプローラー", "表示", "表示", "ファイル名拡張子"],
    steps: [
      "エクスプローラーを開く（Win + E）",
      "上部メニューの「表示」をクリック",
      "「表示」にカーソルを合わせる",
      "「ファイル名拡張子」にチェックを入れる",
    ],
    related_slugs: ["show-hidden-files", "change-default-app"],
    keywords: ["拡張子", "extension", "ファイル名", "表示", "エクスプローラー"],
    description: "ファイルの拡張子（.txt .jpgなど）を表示する方法です。",
  },
  {
    title: "隠しファイルを表示する",
    slug: "show-hidden-files",
    os: "windows11",
    version: "23H2",
    category: "file",
    aliases: ["隠しファイル", "非表示ファイル", "ドットファイル"],
    path: ["エクスプローラー", "表示", "表示", "隠しファイル"],
    steps: [
      "エクスプローラーを開く（Win + E）",
      "上部メニューの「表示」をクリック",
      "「表示」にカーソルを合わせる",
      "「隠しファイル」にチェックを入れる",
    ],
    related_slugs: ["show-file-extensions"],
    keywords: ["隠しファイル", "hidden", "非表示", "ドットファイル"],
    description: "隠しファイル・フォルダを表示する方法です。",
  },
  {
    title: "Bluetooth機器を接続する",
    slug: "connect-bluetooth",
    os: "windows11",
    version: "23H2",
    category: "bluetooth",
    aliases: ["Bluetooth接続", "ブルートゥース", "ワイヤレス接続", "イヤホン接続", "BT"],
    path: ["設定", "Bluetoothとデバイス", "デバイスの追加"],
    steps: [
      "設定を開く（Win + I）",
      "「Bluetoothとデバイス」をクリック",
      "Bluetoothがオンになっていることを確認",
      "「デバイスの追加」をクリック",
      "接続したい機器をペアリングモードにする",
      "一覧から機器を選択して接続",
    ],
    related_slugs: ["bluetooth-troubleshoot", "connect-bluetooth-ios", "connect-bluetooth-macos"],
    keywords: ["Bluetooth", "ブルートゥース", "ペアリング", "ワイヤレス", "イヤホン", "ヘッドホン"],
    description: "Bluetoothでイヤホンやマウスなどを接続する方法です。",
  },
  {
    title: "Bluetoothが繋がらない時の対処",
    slug: "bluetooth-troubleshoot",
    os: "windows11",
    version: "23H2",
    category: "bluetooth",
    aliases: ["Bluetooth繋がらない", "BT不具合", "ペアリングできない"],
    path: ["設定", "Bluetoothとデバイス"],
    steps: [
      "設定 > Bluetoothとデバイス でBluetoothをオフ→オンにする",
      "接続済みの機器を一度「デバイスの削除」で削除する",
      "機器側もペアリング情報をリセットする",
      "再度「デバイスの追加」から接続する",
      "解決しない場合はデバイスマネージャーでBluetoothドライバーを更新する",
    ],
    related_slugs: ["connect-bluetooth"],
    keywords: ["Bluetooth", "繋がらない", "接続できない", "トラブル", "不具合"],
    description: "Bluetooth機器が接続できない場合の対処方法です。",
  },
  {
    title: "画面の明るさを変更する",
    slug: "change-brightness",
    os: "windows11",
    version: "23H2",
    category: "display",
    aliases: ["明るさ", "画面暗く", "画面まぶしい", "輝度", "ブライトネス"],
    path: ["設定", "システム", "ディスプレイ", "明るさ"],
    steps: [
      "設定を開く（Win + I）",
      "「システム」→「ディスプレイ」をクリック",
      "「明るさ」のスライダーで調整",
      "または、アクションセンター（Win + A）から素早く変更可能",
    ],
    related_slugs: ["night-light", "change-brightness-ios", "change-brightness-macos"],
    keywords: ["明るさ", "輝度", "暗い", "まぶしい", "ディスプレイ", "ブライトネス"],
    description: "画面の明るさ（輝度）を調整する方法です。",
  },
  {
    title: "夜間モード（ナイトライト）を設定する",
    slug: "night-light",
    os: "windows11",
    version: "23H2",
    category: "display",
    aliases: ["ナイトライト", "ブルーライト", "夜間モード", "目に優しい"],
    path: ["設定", "システム", "ディスプレイ", "夜間モード"],
    steps: [
      "設定を開く（Win + I）",
      "「システム」→「ディスプレイ」をクリック",
      "「夜間モード」をオンにする",
      "「強さ」スライダーでブルーライトカットの強さを調整",
      "スケジュール設定で自動ON/OFFも可能",
    ],
    related_slugs: ["change-brightness"],
    keywords: ["ナイトライト", "夜間", "ブルーライト", "目", "暖色"],
    description: "画面を暖色にしてブルーライトを軽減する設定です。",
  },
  {
    title: "マイクのアクセスを許可する",
    slug: "allow-microphone",
    os: "windows11",
    version: "23H2",
    category: "privacy",
    aliases: ["マイク許可", "マイク使えない", "音声入力できない", "マイクアクセス"],
    path: ["設定", "プライバシーとセキュリティ", "マイク"],
    steps: [
      "設定を開く（Win + I）",
      "「プライバシーとセキュリティ」をクリック",
      "「マイク」をクリック",
      "「マイクへのアクセス」をオンにする",
      "使いたいアプリのマイク許可もオンにする",
    ],
    related_slugs: ["allow-camera", "allow-microphone-ios", "allow-microphone-macos"],
    keywords: ["マイク", "音声", "許可", "プライバシー", "Teams", "Zoom"],
    description: "アプリがマイクを使えるように許可する方法です。",
  },
  {
    title: "カメラのアクセスを許可する",
    slug: "allow-camera",
    os: "windows11",
    version: "23H2",
    category: "privacy",
    aliases: ["カメラ許可", "カメラ使えない", "ビデオ通話できない"],
    path: ["設定", "プライバシーとセキュリティ", "カメラ"],
    steps: [
      "設定を開く（Win + I）",
      "「プライバシーとセキュリティ」をクリック",
      "「カメラ」をクリック",
      "「カメラへのアクセス」をオンにする",
      "使いたいアプリのカメラ許可もオンにする",
    ],
    related_slugs: ["allow-microphone"],
    keywords: ["カメラ", "ビデオ", "許可", "プライバシー", "Teams", "Zoom"],
    description: "アプリがカメラを使えるように許可する方法です。",
  },
  {
    title: "通知をオフにする",
    slug: "disable-notifications",
    os: "windows11",
    version: "23H2",
    category: "notification",
    aliases: ["通知オフ", "通知消したい", "通知うるさい", "集中モード"],
    path: ["設定", "システム", "通知"],
    steps: [
      "設定を開く（Win + I）",
      "「システム」→「通知」をクリック",
      "全体の通知をオフにするか、アプリ別にオフにする",
      "「応答不可」モードを使えば一時的に通知を止められる",
    ],
    related_slugs: ["disable-notifications-ios", "disable-notifications-macos"],
    keywords: ["通知", "オフ", "消す", "応答不可", "集中", "ノーティフィケーション"],
    description: "不要な通知を止める方法です。",
  },
  {
    title: "DNSサーバーを変更する",
    slug: "change-dns",
    os: "windows11",
    version: "23H2",
    category: "network",
    aliases: ["DNS変更", "DNSサーバー", "ネット速度改善", "1.1.1.1", "8.8.8.8"],
    path: ["設定", "ネットワークとインターネット", "Wi-Fi", "プロパティ", "DNS サーバーの割り当て"],
    steps: [
      "設定を開く（Win + I）",
      "「ネットワークとインターネット」をクリック",
      "接続中のネットワーク（Wi-Fiなど）のプロパティを開く",
      "「DNS サーバーの割り当て」の「編集」をクリック",
      "「手動」に変更し、希望のDNSアドレスを入力（例: 8.8.8.8）",
    ],
    related_slugs: [],
    keywords: ["DNS", "ネットワーク", "速度", "Google DNS", "Cloudflare"],
    description: "DNSサーバーを手動で変更する方法です。",
  },
  {
    title: "デフォルトアプリを変更する",
    slug: "change-default-app",
    os: "windows11",
    version: "23H2",
    category: "app",
    aliases: ["既定のアプリ", "デフォルトブラウザ", "関連付け変更"],
    path: ["設定", "アプリ", "既定のアプリ"],
    steps: [
      "設定を開く（Win + I）",
      "「アプリ」→「既定のアプリ」をクリック",
      "変更したいアプリまたはファイルの種類を検索",
      "新しいデフォルトアプリを選択",
    ],
    related_slugs: ["show-file-extensions"],
    keywords: ["既定", "デフォルト", "ブラウザ", "関連付け", "アプリ"],
    description: "ファイルを開くデフォルトアプリを変更する方法です。",
  },

  // === iOS ===
  {
    title: "Bluetooth機器を接続する",
    slug: "connect-bluetooth-ios",
    os: "ios",
    version: "17",
    category: "bluetooth",
    aliases: ["Bluetooth接続", "ブルートゥース", "AirPods接続", "イヤホン接続"],
    path: ["設定", "Bluetooth"],
    steps: [
      "「設定」アプリを開く",
      "「Bluetooth」をタップ",
      "Bluetoothがオンになっていることを確認",
      "接続したい機器をペアリングモードにする",
      "「その他のデバイス」に表示されたらタップして接続",
    ],
    related_slugs: ["connect-bluetooth", "connect-bluetooth-macos"],
    keywords: ["Bluetooth", "ブルートゥース", "AirPods", "ペアリング", "ワイヤレス"],
    description: "iPhoneでBluetooth機器を接続する方法です。",
  },
  {
    title: "画面の明るさを変更する",
    slug: "change-brightness-ios",
    os: "ios",
    version: "17",
    category: "display",
    aliases: ["明るさ", "画面暗く", "まぶしい", "輝度"],
    path: ["設定", "画面表示と明るさ"],
    steps: [
      "「設定」アプリを開く",
      "「画面表示と明るさ」をタップ",
      "「明るさ」スライダーで調整",
      "またはコントロールセンターで素早く変更可能（右上から下スワイプ）",
    ],
    related_slugs: ["change-brightness", "change-brightness-macos", "night-shift-ios"],
    keywords: ["明るさ", "輝度", "暗い", "まぶしい", "ディスプレイ"],
    description: "iPhoneの画面の明るさを調整する方法です。",
  },
  {
    title: "Night Shift（ブルーライトカット）を設定する",
    slug: "night-shift-ios",
    os: "ios",
    version: "17",
    category: "display",
    aliases: ["ナイトシフト", "ブルーライト", "夜間モード", "目に優しい"],
    path: ["設定", "画面表示と明るさ", "Night Shift"],
    steps: [
      "「設定」アプリを開く",
      "「画面表示と明るさ」をタップ",
      "「Night Shift」をタップ",
      "「時間指定」をオンにするか、「手動で明日まで有効にする」をオンにする",
      "「色温度」スライダーで暖色の強さを調整",
    ],
    related_slugs: ["change-brightness-ios"],
    keywords: ["Night Shift", "ナイトシフト", "ブルーライト", "夜間", "暖色"],
    description: "画面を暖色にしてブルーライトを軽減する設定です。",
  },
  {
    title: "マイクのアクセスを許可する",
    slug: "allow-microphone-ios",
    os: "ios",
    version: "17",
    category: "privacy",
    aliases: ["マイク許可", "マイク使えない", "音声入力", "マイクアクセス"],
    path: ["設定", "プライバシーとセキュリティ", "マイク"],
    steps: [
      "「設定」アプリを開く",
      "「プライバシーとセキュリティ」をタップ",
      "「マイク」をタップ",
      "マイクを許可したいアプリのスイッチをオンにする",
    ],
    related_slugs: ["allow-microphone", "allow-microphone-macos"],
    keywords: ["マイク", "音声", "許可", "プライバシー"],
    description: "アプリがマイクを使えるように許可する方法です。",
  },
  {
    title: "通知をオフにする",
    slug: "disable-notifications-ios",
    os: "ios",
    version: "17",
    category: "notification",
    aliases: ["通知オフ", "通知消したい", "通知うるさい", "集中モード", "おやすみモード"],
    path: ["設定", "通知"],
    steps: [
      "「設定」アプリを開く",
      "「通知」をタップ",
      "通知をオフにしたいアプリをタップ",
      "「通知を許可」のスイッチをオフにする",
      "全体を止めたい場合は「集中モード」を使う",
    ],
    related_slugs: ["disable-notifications", "disable-notifications-macos"],
    keywords: ["通知", "オフ", "消す", "集中モード", "おやすみ"],
    description: "不要な通知を止める方法です。",
  },
  {
    title: "Wi-Fiに接続する",
    slug: "connect-wifi-ios",
    os: "ios",
    version: "17",
    category: "network",
    aliases: ["Wi-Fi接続", "WiFi", "ワイファイ", "ネット繋がらない"],
    path: ["設定", "Wi-Fi"],
    steps: [
      "「設定」アプリを開く",
      "「Wi-Fi」をタップ",
      "Wi-Fiをオンにする",
      "接続したいネットワーク名をタップ",
      "パスワードを入力して「接続」をタップ",
    ],
    related_slugs: [],
    keywords: ["Wi-Fi", "WiFi", "ワイファイ", "接続", "ネットワーク", "パスワード"],
    description: "iPhoneをWi-Fiに接続する方法です。",
  },

  // === macOS ===
  {
    title: "Bluetooth機器を接続する",
    slug: "connect-bluetooth-macos",
    os: "macos",
    version: "Sonoma",
    category: "bluetooth",
    aliases: ["Bluetooth接続", "ブルートゥース", "AirPods接続", "ワイヤレス接続"],
    path: ["システム設定", "Bluetooth"],
    steps: [
      "Appleメニュー（）→「システム設定」を開く",
      "「Bluetooth」をクリック",
      "Bluetoothがオンになっていることを確認",
      "接続したい機器をペアリングモードにする",
      "「近くのデバイス」に表示されたら「接続」をクリック",
    ],
    related_slugs: ["connect-bluetooth", "connect-bluetooth-ios"],
    keywords: ["Bluetooth", "ブルートゥース", "AirPods", "ペアリング", "ワイヤレス"],
    description: "MacでBluetooth機器を接続する方法です。",
  },
  {
    title: "画面の明るさを変更する",
    slug: "change-brightness-macos",
    os: "macos",
    version: "Sonoma",
    category: "display",
    aliases: ["明るさ", "画面暗く", "まぶしい", "輝度"],
    path: ["システム設定", "ディスプレイ"],
    steps: [
      "Appleメニュー（）→「システム設定」を開く",
      "「ディスプレイ」をクリック",
      "「輝度」スライダーで調整",
      "またはキーボードの輝度キー（F1/F2）で変更可能",
    ],
    related_slugs: ["change-brightness", "change-brightness-ios"],
    keywords: ["明るさ", "輝度", "暗い", "まぶしい", "ディスプレイ"],
    description: "Macの画面の明るさを調整する方法です。",
  },
  {
    title: "マイクのアクセスを許可する",
    slug: "allow-microphone-macos",
    os: "macos",
    version: "Sonoma",
    category: "privacy",
    aliases: ["マイク許可", "マイク使えない", "音声入力", "マイクアクセス"],
    path: ["システム設定", "プライバシーとセキュリティ", "マイク"],
    steps: [
      "Appleメニュー（）→「システム設定」を開く",
      "「プライバシーとセキュリティ」をクリック",
      "「マイク」をクリック",
      "マイクを許可したいアプリのスイッチをオンにする",
    ],
    related_slugs: ["allow-microphone", "allow-microphone-ios"],
    keywords: ["マイク", "音声", "許可", "プライバシー"],
    description: "アプリがマイクを使えるように許可する方法です。",
  },
  {
    title: "通知をオフにする",
    slug: "disable-notifications-macos",
    os: "macos",
    version: "Sonoma",
    category: "notification",
    aliases: ["通知オフ", "通知消したい", "通知うるさい", "集中モード", "おやすみモード"],
    path: ["システム設定", "通知"],
    steps: [
      "Appleメニュー（）→「システム設定」を開く",
      "「通知」をクリック",
      "通知をオフにしたいアプリをクリック",
      "「通知を許可」のスイッチをオフにする",
      "全体を止めたい場合は「集中モード」を使う",
    ],
    related_slugs: ["disable-notifications", "disable-notifications-ios"],
    keywords: ["通知", "オフ", "消す", "集中モード", "おやすみ"],
    description: "不要な通知を止める方法です。",
  },
  {
    title: "Dockを自動的に隠す",
    slug: "auto-hide-dock",
    os: "macos",
    version: "Sonoma",
    category: "display",
    aliases: ["Dock非表示", "Dock隠す", "画面広く", "Dock自動"],
    path: ["システム設定", "デスクトップとDock"],
    steps: [
      "Appleメニュー（）→「システム設定」を開く",
      "「デスクトップとDock」をクリック",
      "「Dockを自動的に表示/非表示」をオンにする",
    ],
    related_slugs: [],
    keywords: ["Dock", "非表示", "隠す", "自動", "デスクトップ"],
    description: "Dockを自動的に隠して画面を広く使う方法です。",
  },
];

// === 追加データ Windows 11 ===
export const additionalSettings: Omit<Setting, "id" | "updated_at">[] = [
  {
    title: "スタートアップアプリを管理する",
    slug: "manage-startup-apps",
    os: "windows11",
    version: "23H2",
    category: "system",
    aliases: ["起動時に起動するアプリ", "スタートアップ無効", "起動遅い", "自動起動"],
    path: ["タスクマネージャー", "スタートアップ アプリ"],
    steps: [
      "Ctrl + Shift + Esc でタスクマネージャーを開く",
      "「スタートアップ アプリ」タブをクリック",
      "無効にしたいアプリを右クリック",
      "「無効にする」を選択",
    ],
    related_slugs: [],
    keywords: ["スタートアップ", "自動起動", "起動", "タスクマネージャー", "遅い"],
    description: "PCの起動時に自動で立ち上がるアプリを管理する方法です。",
  },
  {
    title: "スリープ時間を変更する",
    slug: "change-sleep-time",
    os: "windows11",
    version: "23H2",
    category: "system",
    aliases: ["スリープ設定", "画面が消える", "電源設定", "スリープしない"],
    path: ["設定", "システム", "電源", "スクリーンとスリープ"],
    steps: [
      "設定を開く（Win + I）",
      "「システム」→「電源」をクリック",
      "「スクリーンとスリープ」を展開",
      "スリープの時間をドロップダウンで変更",
    ],
    related_slugs: [],
    keywords: ["スリープ", "電源", "画面消える", "省電力", "スクリーン"],
    description: "PCが自動でスリープに入るまでの時間を変更する方法です。",
  },
  {
    title: "Windowsの壁紙を変更する",
    slug: "change-wallpaper",
    os: "windows11",
    version: "23H2",
    category: "display",
    aliases: ["背景変更", "デスクトップ背景", "壁紙", "バックグラウンド"],
    path: ["設定", "個人用設定", "背景"],
    steps: [
      "デスクトップを右クリック",
      "「個人用設定」をクリック",
      "「背景」をクリック",
      "「画像」「単色」「スライドショー」から選んで設定",
    ],
    related_slugs: [],
    keywords: ["壁紙", "背景", "デスクトップ", "個人用設定"],
    description: "デスクトップの背景（壁紙）を変更する方法です。",
  },
  {
    title: "タスクバーの位置を変更する",
    slug: "taskbar-position",
    os: "windows11",
    version: "23H2",
    category: "display",
    aliases: ["タスクバー移動", "タスクバー下", "タスクバー左", "バーの位置"],
    path: ["設定", "個人用設定", "タスクバー", "タスクバーの動作"],
    steps: [
      "設定を開く（Win + I）",
      "「個人用設定」→「タスクバー」をクリック",
      "下にスクロールして「タスクバーの動作」を展開",
      "「タスクバーの配置」で「左揃え」または「中央揃え」を選択",
    ],
    related_slugs: ["change-wallpaper"],
    keywords: ["タスクバー", "位置", "配置", "左揃え", "中央"],
    description: "タスクバーのアイコンの配置を左右どちらかに変更する方法です。",
  },
  {
    title: "キーボードの言語・入力ソースを追加する",
    slug: "add-keyboard-language",
    os: "windows11",
    version: "23H2",
    category: "input",
    aliases: ["英語キーボード", "言語追加", "IME", "入力方式"],
    path: ["設定", "時刻と言語", "言語と地域"],
    steps: [
      "設定を開く（Win + I）",
      "「時刻と言語」→「言語と地域」をクリック",
      "「言語を追加する」をクリック",
      "追加したい言語を検索して選択",
    ],
    related_slugs: [],
    keywords: ["キーボード", "言語", "英語", "IME", "入力"],
    description: "英語キーボードなど追加の言語・入力ソースを設定する方法です。",
  },
  {
    title: "音量を変更する",
    slug: "change-volume",
    os: "windows11",
    version: "23H2",
    category: "sound",
    aliases: ["音量設定", "ボリューム", "音が出ない", "音小さい", "スピーカー音量"],
    path: ["タスクバー右下", "スピーカーアイコン"],
    steps: [
      "タスクバー右下のスピーカーアイコンをクリック",
      "スライダーで音量を調整",
      "またはアクションセンター（Win + A）から調整可能",
    ],
    related_slugs: ["set-audio-output"],
    keywords: ["音量", "ボリューム", "スピーカー", "サウンド", "音"],
    description: "PCの音量を変更する方法です。",
  },
  {
    title: "既定のオーディオ出力デバイスを変更する",
    slug: "set-audio-output",
    os: "windows11",
    version: "23H2",
    category: "sound",
    aliases: ["スピーカー切り替え", "ヘッドホン出力", "音声出力先", "サウンド設定"],
    path: ["設定", "システム", "サウンド"],
    steps: [
      "設定を開く（Win + I）",
      "「システム」→「サウンド」をクリック",
      "「出力」セクションでデバイスを選択",
    ],
    related_slugs: ["change-volume"],
    keywords: ["オーディオ", "出力", "スピーカー", "ヘッドホン", "サウンド"],
    description: "音声の出力先（スピーカーやヘッドホン）を切り替える方法です。",
  },
  {
    title: "画面の解像度を変更する",
    slug: "change-resolution",
    os: "windows11",
    version: "23H2",
    category: "display",
    aliases: ["解像度変更", "画面サイズ", "1080p", "4K設定", "ディスプレイ解像度"],
    path: ["設定", "システム", "ディスプレイ", "画面の解像度"],
    steps: [
      "設定を開く（Win + I）",
      "「システム」→「ディスプレイ」をクリック",
      "下にスクロールして「画面の解像度」を選択",
      "ドロップダウンから解像度を選ぶ",
    ],
    related_slugs: ["change-brightness"],
    keywords: ["解像度", "1080p", "4K", "ディスプレイ", "画面"],
    description: "画面の解像度（ピクセル数）を変更する方法です。",
  },
  {
    title: "Windowsのバージョンを確認する",
    slug: "check-windows-version",
    os: "windows11",
    version: "23H2",
    category: "system",
    aliases: ["Windowsバージョン確認", "ビルド番号", "OS確認", "winver"],
    path: ["設定", "システム", "バージョン情報"],
    steps: [
      "Win + R を押して「winver」と入力してEnter",
      "またはWin + I で設定を開き「システム」→「バージョン情報」を確認",
    ],
    related_slugs: [],
    keywords: ["バージョン", "確認", "winver", "ビルド", "システム"],
    description: "Windowsのバージョンやビルド番号を確認する方法です。",
  },
  {
    title: "Windowsアップデートを手動で確認する",
    slug: "check-windows-update",
    os: "windows11",
    version: "23H2",
    category: "system",
    aliases: ["アップデート確認", "Windows更新", "WU", "更新プログラム"],
    path: ["設定", "Windows Update"],
    steps: [
      "設定を開く（Win + I）",
      "「Windows Update」をクリック",
      "「更新プログラムの確認」ボタンをクリック",
    ],
    related_slugs: [],
    keywords: ["アップデート", "更新", "Windows Update", "最新"],
    description: "Windowsのアップデートを手動で確認・適用する方法です。",
  },
  // iOS追加
  {
    title: "FaceIDを設定する",
    slug: "setup-faceid",
    os: "ios",
    version: "17",
    category: "security",
    aliases: ["顔認証", "FaceID設定", "顔ロック解除", "顔で開く"],
    path: ["設定", "Face IDとパスコード"],
    steps: [
      "「設定」アプリを開く",
      "「Face IDとパスコード」をタップ",
      "「Face IDを設定」をタップ",
      "画面の指示に従って顔をスキャン",
    ],
    related_slugs: ["setup-touchid"],
    keywords: ["FaceID", "顔認証", "生体認証", "セキュリティ", "ロック"],
    description: "iPhoneのFace IDを設定する方法です。",
  },
  {
    title: "TouchIDを設定する",
    slug: "setup-touchid",
    os: "ios",
    version: "17",
    category: "security",
    aliases: ["指紋認証", "TouchID設定", "指で開く", "指紋ロック"],
    path: ["設定", "Touch IDとパスコード"],
    steps: [
      "「設定」アプリを開く",
      "「Touch IDとパスコード」をタップ",
      "「指紋を追加」をタップ",
      "ホームボタンに指を置いてスキャン",
    ],
    related_slugs: ["setup-faceid"],
    keywords: ["TouchID", "指紋", "生体認証", "セキュリティ"],
    description: "iPhoneの指紋認証（Touch ID）を設定する方法です。",
  },
  {
    title: "モバイルデータ通信をオフにする",
    slug: "disable-cellular-ios",
    os: "ios",
    version: "17",
    category: "network",
    aliases: ["データ通信オフ", "通信量節約", "モバイル通信", "4G LTE"],
    path: ["設定", "モバイル通信"],
    steps: [
      "「設定」アプリを開く",
      "「モバイル通信」をタップ",
      "「モバイルデータ通信」をオフにする",
    ],
    related_slugs: ["connect-wifi-ios"],
    keywords: ["モバイルデータ", "通信量", "LTE", "4G", "5G"],
    description: "モバイルデータ通信をオフにしてデータ消費を抑える方法です。",
  },
  {
    title: "位置情報サービスを管理する",
    slug: "location-services-ios",
    os: "ios",
    version: "17",
    category: "privacy",
    aliases: ["位置情報オフ", "GPS設定", "プライバシー位置", "場所の許可"],
    path: ["設定", "プライバシーとセキュリティ", "位置情報サービス"],
    steps: [
      "「設定」アプリを開く",
      "「プライバシーとセキュリティ」をタップ",
      "「位置情報サービス」をタップ",
      "全体のオン/オフ、またはアプリ別に「なし」「次回のみ」「使用中のみ」「常に」を選択",
    ],
    related_slugs: ["allow-microphone-ios"],
    keywords: ["位置情報", "GPS", "プライバシー", "場所"],
    description: "アプリの位置情報アクセスを管理する方法です。",
  },
  {
    title: "スクリーンタイムを設定する",
    slug: "screen-time-ios",
    os: "ios",
    version: "17",
    category: "system",
    aliases: ["使用時間制限", "スクリーンタイム", "子供制限", "アプリ制限"],
    path: ["設定", "スクリーンタイム"],
    steps: [
      "「設定」アプリを開く",
      "「スクリーンタイム」をタップ",
      "「スクリーンタイムをオンにする」をタップ",
      "アプリカテゴリ別の使用時間制限などを設定",
    ],
    related_slugs: [],
    keywords: ["スクリーンタイム", "使用時間", "制限", "子供", "ペアレンタル"],
    description: "iPhoneの使用時間を管理・制限する方法です。",
  },
  {
    title: "ストレージの使用状況を確認する",
    slug: "check-storage-ios",
    os: "ios",
    version: "17",
    category: "storage",
    aliases: ["容量確認", "空き容量", "ストレージ不足", "容量足りない"],
    path: ["設定", "一般", "iPhoneストレージ"],
    steps: [
      "「設定」アプリを開く",
      "「一般」をタップ",
      "「iPhoneストレージ」をタップ",
      "アプリ別の使用容量を確認",
    ],
    related_slugs: [],
    keywords: ["ストレージ", "容量", "空き", "GB", "保存"],
    description: "iPhoneのストレージ（容量）の使用状況を確認する方法です。",
  },
  // macOS追加
  {
    title: "Mission Controlでウィンドウを管理する",
    slug: "mission-control",
    os: "macos",
    version: "Sonoma",
    category: "system",
    aliases: ["ミッションコントロール", "ウィンドウ一覧", "仮想デスクトップ"],
    path: ["システム設定", "デスクトップとDock", "Mission Control"],
    steps: [
      "トラックパッドで3本指上スワイプ（またはControl + ↑）",
      "すべてのウィンドウが一覧表示される",
      "上部にスペース（仮想デスクトップ）を追加可能",
    ],
    related_slugs: ["auto-hide-dock"],
    keywords: ["Mission Control", "ウィンドウ", "仮想デスクトップ", "スペース"],
    description: "すべてのウィンドウを一覧表示・整理する方法です。",
  },
  {
    title: "トラックパッドのジェスチャーを設定する",
    slug: "trackpad-gestures",
    os: "macos",
    version: "Sonoma",
    category: "input",
    aliases: ["トラックパッド設定", "スクロール方向", "ジェスチャー", "タップでクリック"],
    path: ["システム設定", "トラックパッド"],
    steps: [
      "Appleメニュー（）→「システム設定」を開く",
      "「トラックパッド」をクリック",
      "「ポイントとクリック」「スクロールとズーム」「その他のジェスチャー」タブで設定",
    ],
    related_slugs: [],
    keywords: ["トラックパッド", "ジェスチャー", "スクロール", "タップ", "スワイプ"],
    description: "トラックパッドのジェスチャーをカスタマイズする方法です。",
  },
  {
    title: "ストレージの使用状況を確認する",
    slug: "check-storage-macos",
    os: "macos",
    version: "Sonoma",
    category: "storage",
    aliases: ["容量確認", "空き容量", "ストレージ不足", "ディスク容量"],
    path: ["Appleメニュー", "このMacについて", "ストレージ"],
    steps: [
      "Appleメニュー（）をクリック",
      "「このMacについて」をクリック",
      "「ストレージ」タブをクリック",
      "カテゴリ別の使用容量を確認",
    ],
    related_slugs: [],
    keywords: ["ストレージ", "容量", "空き", "ディスク", "GB"],
    description: "Macのストレージ（容量）の使用状況を確認する方法です。",
  },
  {
    title: "スクリーンショットを撮る",
    slug: "screenshot-macos",
    os: "macos",
    version: "Sonoma",
    category: "system",
    aliases: ["スクショ", "画面キャプチャ", "画面保存", "スクリーンキャプチャ"],
    path: ["キーボードショートカット"],
    steps: [
      "全画面：Shift + Command + 3",
      "範囲指定：Shift + Command + 4 → ドラッグ",
      "ウィンドウ指定：Shift + Command + 4 → Space → クリック",
      "画面収録なども含めたパネル：Shift + Command + 5",
    ],
    related_slugs: [],
    keywords: ["スクリーンショット", "スクショ", "キャプチャ", "Command+Shift+3", "画面"],
    description: "Macでスクリーンショットを撮る方法です。",
  },
  {
    title: "Spotlight検索を使う",
    slug: "spotlight-search",
    os: "macos",
    version: "Sonoma",
    category: "system",
    aliases: ["スポットライト", "ファイル検索", "アプリ起動", "Command+Space"],
    path: ["キーボードショートカット", "Command + Space"],
    steps: [
      "Command + Space でSpotlightを開く",
      "検索したいファイル名・アプリ名・計算式などを入力",
      "Enterで開く、またはCommand+Enterでファインダーで表示",
    ],
    related_slugs: [],
    keywords: ["Spotlight", "検索", "ファイル", "アプリ", "Command+Space"],
    description: "MacのSpotlight検索でファイルやアプリをすばやく開く方法です。",
  },
];
