-- 主対象（Windows 11 / iPhone / Android）の接続トラブル記事
-- supabase-schema.sql または supabase-upgrade-operations.sql の実行後に適用する。

INSERT INTO settings
  (title, slug, os, version, category, difficulty, estimate_minutes,
   aliases, path, steps, related_slugs, keywords, description,
   status, published_at, verified_at, source_url, device_scope, impact, rollback)
VALUES
  ('Wi-Fiが切れる・つながらないときの対処', 'wifi-troubleshoot-windows11', 'windows11', '25H2', 'network', 'beginner', 5,
   ARRAY['Wi-Fi切れる','WiFi切れる','Wi-Fiつながらない','WiFi繋がらない','ネット切れる','Wi-Fi不安定'],
   ARRAY['設定','ネットワークとインターネット','Wi-Fi'],
   '["タスクバーのネットワークアイコンをクリックし、Wi-Fiをいったんオフ→オンにする","設定（Win + I）→「ネットワークとインターネット」→「Wi-Fi」で接続先を確認する","接続先を選び、「切断」してから再接続する","改善しない場合は「既知のネットワークの管理」から対象Wi-Fiを選び、「削除」してパスワードを入力し直す","複数の端末で切れる場合は、ルーターを再起動してから再確認する"]'::jsonb,
   ARRAY['change-dns'], ARRAY['Wi-Fi','WiFi','無線LAN','接続','切断','インターネット','ネットワーク','トラブル'],
   'Windows 11でWi-Fiが切れる、つながらない、接続が不安定なときに確認する順番です。',
   'published', NOW(), '2026-08-13T00:00:00Z'::timestamptz,
   'https://support.microsoft.com/en-us/windows/experience/connectivity-networking/connect-to-a-wi-fi-network-in-windows',
   'Windows 11 25H2。PCメーカーの無線ドライバーやルーターによって表示が異なる場合があります。',
   'Wi-Fiの登録を削除すると、再接続時にパスワードの入力が必要です。',
   '削除したWi-Fiを一覧から選び、パスワードを入力して再登録します。'),
  ('Wi-Fiが切れる・つながらないときの対処', 'wifi-troubleshoot-ios', 'ios', '26', 'network', 'beginner', 5,
   ARRAY['Wi-Fi切れる','WiFi切れる','Wi-Fiつながらない','WiFi繋がらない','ネット切れる','Wi-Fi不安定'],
   ARRAY['設定','Wi-Fi'],
   '["「設定」→「Wi-Fi」を開き、Wi-Fiをいったんオフ→オンにする","接続先のネットワーク名をタップし、「このネットワーク設定を削除」を選ぶ","確認画面で削除したあと、同じネットワークを選び、パスワードを入力して再接続する","改善しない場合はiPhoneを再起動し、ルーターに近い場所で再確認する","どのWi-Fiにもつながらない場合は、Appleの公式サポート手順を確認する"]'::jsonb,
   ARRAY['connect-wifi-ios'], ARRAY['Wi-Fi','WiFi','無線LAN','接続','切断','インターネット','ネットワーク','トラブル'],
   'iPhoneでWi-Fiが切れる、つながらない、接続が不安定なときの確認手順です。',
   'published', NOW(), '2026-08-13T00:00:00Z'::timestamptz,
   'https://support.apple.com/en-us/111786',
   'iOS 26。iOSのバージョンやネットワーク構成により項目名が異なる場合があります。',
   'ネットワーク設定を削除すると、保存済みパスワードが消える場合があります。',
   '同じネットワークを選び、Wi-Fiパスワードを入力して再接続します。'),
  ('Wi-Fiが切れる・つながらないときの対処', 'wifi-troubleshoot-android', 'android', '16', 'network', 'beginner', 5,
   ARRAY['Wi-Fi切れる','WiFi切れる','Wi-Fiつながらない','WiFi繋がらない','ネット切れる','Wi-Fi不安定'],
   ARRAY['設定','ネットワークとインターネット','インターネット'],
   '["「設定」→「ネットワークとインターネット」→「インターネット」を開く","Wi-Fiをいったんオフ→オンにし、接続先を選び直す","接続先を長押しして保存済みネットワークから削除し、パスワードを入力して再接続する","クイック設定の「インターネット」から「リセット」が表示される場合は、接続をリセットする","複数の端末で切れる場合は、ルーターを再起動してから再確認する"]'::jsonb,
   ARRAY['connect-wifi-android'], ARRAY['Wi-Fi','WiFi','無線LAN','接続','切断','インターネット','ネットワーク','トラブル'],
   'AndroidスマートフォンでWi-Fiが切れる、つながらない、接続が不安定なときの確認手順です。',
   'published', NOW(), '2026-08-13T00:00:00Z'::timestamptz,
   'https://support.google.com/android/answer/2651367?hl=ja',
   'Android 16の標準的な設定画面（Pixel系）を基準にしています。Galaxyなどでは項目名が異なります。',
   '保存済みネットワークを削除すると、再接続時にパスワードの入力が必要です。',
   '削除したWi-Fiを一覧から選び、パスワードを入力して再登録します。')

ON CONFLICT (slug, os) DO UPDATE SET
  title = EXCLUDED.title,
  version = EXCLUDED.version,
  category = EXCLUDED.category,
  difficulty = EXCLUDED.difficulty,
  estimate_minutes = EXCLUDED.estimate_minutes,
  aliases = EXCLUDED.aliases,
  path = EXCLUDED.path,
  steps = EXCLUDED.steps,
  related_slugs = EXCLUDED.related_slugs,
  keywords = EXCLUDED.keywords,
  description = EXCLUDED.description,
  status = EXCLUDED.status,
  published_at = COALESCE(settings.published_at, EXCLUDED.published_at),
  verified_at = EXCLUDED.verified_at,
  source_url = EXCLUDED.source_url,
  device_scope = EXCLUDED.device_scope,
  impact = EXCLUDED.impact,
  rollback = EXCLUDED.rollback,
  updated_at = NOW();
