// Windows 11で使うMicrosoft 365アプリの設定候補。
// 管理画面の「追加候補を下書き保存」から、既存記事を変更せず追加する。
const microsoft365Settings = [
  { title: "Teamsの通知を設定する", slug: "teams-notifications", os: "windows11", version: "Microsoft Teams", category: "app", difficulty: "beginner", estimate_minutes: 2,
    aliases: ["Teams通知", "Teamsうるさい", "Teams通知オフ", "チームス通知", "Teamsバナー"],
    path: ["Microsoft Teams", "プロフィール画像", "設定", "通知とアクティビティ"],
    steps: ["Teams右上のプロフィール画像の横にある「…」をクリック", "「設定」を開く", "「通知とアクティビティ」を選択", "チャット・メンション・会議などの通知を必要に応じて変更", "必要なら「すべての通知をミュート」をオンにする"],
    related_slugs: ["disable-notifications", "allow-microphone", "allow-camera"], keywords: ["Teams", "通知", "ミュート", "バナー", "会議", "チャット", "メンション"], description: "Microsoft Teamsのチャット・メンション・会議通知を調整する方法です。" },
  { title: "TeamsをWindows起動時に自動起動しない", slug: "disable-teams-autostart", os: "windows11", version: "Microsoft Teams", category: "app", difficulty: "beginner", estimate_minutes: 2,
    aliases: ["Teams自動起動オフ", "Teams勝手に起動", "Teams起動しない", "Teamsスタートアップ"],
    path: ["Microsoft Teams", "プロフィール画像", "設定", "一般", "システム"],
    steps: ["Teams右上のプロフィール画像の横にある「…」をクリック", "「設定」→「一般」を開く", "「Teamsを自動的に起動する」をオフにする", "必要に応じてバックグラウンドで実行する設定もオフにする", "Teamsを再起動して反映を確認する"],
    related_slugs: ["manage-startup-apps", "teams-notifications"], keywords: ["Teams", "自動起動", "スタートアップ", "勝手に起動", "バックグラウンド"], description: "Windows起動時にMicrosoft Teamsが自動で開かないようにする方法です。" },
  { title: "Teamsのカメラとマイクを確認する", slug: "teams-camera-microphone", os: "windows11", version: "Microsoft Teams", category: "app", difficulty: "beginner", estimate_minutes: 3,
    aliases: ["Teamsカメラ映らない", "Teamsマイク使えない", "Teams会議音声", "Teamsデバイス設定"],
    path: ["Microsoft Teams", "プロフィール画像", "設定", "デバイス"],
    steps: ["Teamsで「…」→「設定」→「デバイス」を開く", "スピーカー・マイク・カメラが正しい機器になっているか確認", "「テスト通話を開始」で音声を確認", "カメラが映らない場合はWindowsのカメラ許可も確認", "マイクが反応しない場合はWindowsのマイク許可も確認"],
    related_slugs: ["allow-microphone", "allow-camera", "adjust-microphone-volume"], keywords: ["Teams", "カメラ", "マイク", "会議", "デバイス", "テスト通話"], description: "Teams会議で使うカメラ・マイク・スピーカーを確認する方法です。" },
  { title: "新しいOutlookの通知をオン・オフする", slug: "outlook-new-notifications", os: "windows11", version: "新しい Outlook", category: "app", difficulty: "beginner", estimate_minutes: 2,
    aliases: ["Outlook通知", "メール通知オフ", "Outlookポップアップ", "新しいOutlook通知"],
    path: ["新しい Outlook", "表示", "表示の設定", "全般", "通知"],
    steps: ["新しいOutlookを開く", "「表示」→「表示の設定」を開く", "「全般」→「通知」を選択", "メール・予定表・ドキュメントの通知をオンまたはオフにする", "通知が届かない場合はWindowsの「システム」→「通知」も確認する"],
    related_slugs: ["disable-notifications", "teams-notifications"], keywords: ["Outlook", "通知", "メール", "ポップアップ", "新しいOutlook", "予定表"], description: "新しいOutlook for Windowsでメールや予定表の通知を設定する方法です。" },
  { title: "クラシックOutlookのデスクトップ通知を設定する", slug: "outlook-desktop-alert", os: "windows11", version: "Outlook Classic", category: "app", difficulty: "beginner", estimate_minutes: 2,
    aliases: ["Outlookデスクトップ通知", "Outlookポップアップ", "メール受信通知", "Outlookアラート"],
    path: ["Outlook", "ファイル", "オプション", "メール", "メッセージの受信"],
    steps: ["クラシックOutlookを開く", "「ファイル」→「オプション」を開く", "左側の「メール」を選択", "「メッセージの受信」にある「デスクトップ通知を表示する」をオンまたはオフにする", "「OK」で保存する"],
    related_slugs: ["outlook-new-notifications", "disable-notifications"], keywords: ["Outlook", "デスクトップ通知", "メール", "ポップアップ", "クラシックOutlook"], description: "クラシックOutlookのメール受信時デスクトップ通知を設定する方法です。" },
  { title: "Outlookの予定表リマインダーを変更する", slug: "outlook-calendar-reminder", os: "windows11", version: "Outlook", category: "app", difficulty: "beginner", estimate_minutes: 2,
    aliases: ["Outlookリマインダー", "予定表通知", "会議通知", "予定通知時間"],
    path: ["Outlook", "予定表", "予定または会議を開く", "リマインダー"],
    steps: ["Outlookで予定表を開く", "変更したい予定または会議を開く", "「リマインダー」の時間を選ぶ", "不要な場合は「なし」を選択", "保存して閉じる"],
    related_slugs: ["outlook-new-notifications", "teams-notifications"], keywords: ["Outlook", "予定表", "リマインダー", "会議", "通知", "アラーム"], description: "Outlookの予定・会議のリマインダー通知時間を変更する方法です。" },
  { title: "Excelの自動保存をオンにする", slug: "excel-autosave", os: "windows11", version: "Excel for Microsoft 365", category: "app", difficulty: "beginner", estimate_minutes: 2,
    aliases: ["Excel自動保存", "Excel保存忘れ", "Excelオートセーブ", "Excel上書き保存"],
    path: ["Excel", "ファイル", "オプション", "保存"],
    steps: ["Excelで対象のファイルを開く", "OneDriveまたはSharePointにファイルを保存する", "ウィンドウ左上の「自動保存」スイッチをオンにする", "既定の保存間隔は「ファイル」→「オプション」→「保存」で確認する", "共有ファイルでは意図しない変更も保存されるため必要に応じてバージョン履歴を確認する"],
    related_slugs: ["setup-onedrive"], keywords: ["Excel", "自動保存", "AutoSave", "保存", "OneDrive", "SharePoint"], description: "Excelの自動保存を有効にして保存忘れを防ぐ方法です。" },
  { title: "Excelの計算方法を自動に戻す", slug: "excel-calculation-mode", os: "windows11", version: "Excel", category: "app", difficulty: "intermediate", estimate_minutes: 2,
    aliases: ["Excel計算されない", "Excel数式更新されない", "Excel再計算", "Excel手動計算"],
    path: ["Excel", "数式", "計算方法の設定", "自動"],
    steps: ["Excelで「数式」タブを開く", "「計算方法の設定」を選択", "「自動」を選択する", "必要に応じてF9キーで再計算する", "大きなブックでは再計算に時間がかかることを確認する"],
    related_slugs: [], keywords: ["Excel", "計算", "数式", "再計算", "F9", "手動計算"], description: "Excelの数式が更新されない場合に、計算方法を自動へ戻す方法です。" },
  { title: "Excelの既定保存形式を変更する", slug: "excel-default-file-format", os: "windows11", version: "Excel", category: "app", difficulty: "beginner", estimate_minutes: 2,
    aliases: ["Excel保存形式", "ExcelCSV保存", "Excelデフォルト拡張子", "Excelファイル形式"],
    path: ["Excel", "ファイル", "オプション", "保存", "この形式でファイルを保存"],
    steps: ["Excelで「ファイル」→「オプション」を開く", "左側の「保存」を選択", "「この形式でファイルを保存」の一覧を開く", "必要な形式（Excelブック、CSVなど）を選択", "「OK」で保存する"],
    related_slugs: ["show-file-extensions"], keywords: ["Excel", "保存形式", "CSV", "xlsx", "拡張子", "既定"], description: "Excelで新規ファイルを保存する際の既定ファイル形式を変更する方法です。" },
  { title: "OneDriveのファイルオンデマンドを設定する", slug: "onedrive-files-on-demand", os: "windows11", version: "OneDrive", category: "file", difficulty: "beginner", estimate_minutes: 2,
    aliases: ["OneDrive容量不足", "OneDriveファイルオンデマンド", "OneDriveローカル容量", "OneDrive雲マーク"],
    path: ["タスクバー", "OneDriveの雲アイコン", "設定", "同期とバックアップ", "詳細設定"],
    steps: ["タスクバーのOneDrive雲アイコンをクリック", "「設定」を開く", "「同期とバックアップ」→「詳細設定」を開く", "「ファイルをオンデマンド」をオンにする", "必要なファイルだけ右クリックして「このデバイス上で常に保持する」を選択する"],
    related_slugs: ["setup-onedrive", "check-disk-storage"], keywords: ["OneDrive", "ファイルオンデマンド", "容量", "クラウド", "同期", "空き容量"], description: "OneDriveのファイルオンデマンドを使い、PCの空き容量を節約する方法です。" },
];

export { microsoft365Settings };
